using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(true)]
[assembly: ComVisibleAttribute(false)]
//[assembly: AllowPartiallyTrustedCallersAttribute()]
[assembly: SecurityPermissionAttribute(SecurityAction.RequestMinimum)]
[assembly: AssemblyCompanyAttribute("http://springsource.org/spring-amqp/")]
[assembly: AssemblyCopyrightAttribute("Copyright 2011 SpringSource.")]
[assembly: AssemblyTrademarkAttribute("Apache License, Version 2.0")]
[assembly: AssemblyCultureAttribute("")]
[assembly: AssemblyVersionAttribute("1.0.0.0")]
[assembly: AssemblyConfigurationAttribute("net-4.0; 1.0.0.0; dev")]

